### PR TITLE
Catch GenericFileException in Generate

### LINKED ISSUE #487: Preview:generate-all crashes at the same image repeatedly
Running `nohup sudo -u www-data php /var/www/html/occ preview:generate-all -vvv &` crashes at a fixed point with a random error. I started it again and it would quickly go through all images, finally crashing as seen here.

Note all images (also correctly processed ones) are in external storage accessed via sftp.

```
2024-06-29T11:35:11+00:00 Generating previews for /.../IMG_20191209-WA0012.jpg
2024-06-29T11:35:11+00:00 Generating previews for /.../IMG_20191209-WA0014.jpg
2024-06-29T11:35:11+00:00 Generating previews for /.../IMG_20191209-WA0015.jpg
2024-06-29T11:35:11+00:00 Generating previews for /.../IMG_20191209-WA0016.jpg
2024-06-29T11:35:11+00:00 Generating previews for /.../IMG_20191209-WA0017.jpg
2024-06-29T11:35:11+00:00 Generating previews for /.../IMG_20191209-WA0019.jpg
2024-06-29T11:35:11+00:00 
2024-06-29T11:35:11+00:00 In File.php line 56:
2024-06-29T11:35:11+00:00                                     
2024-06-29T11:35:11+00:00   [OCP\Files\GenericFileException]  
2024-06-29T11:35:11+00:00                                     
2024-06-29T11:35:11+00:00 
2024-06-29T11:35:11+00:00 Exception trace:
2024-06-29T11:35:11+00:00   at /var/www/html/lib/private/Files/Node/File.php:56
2024-06-29T11:35:11+00:00  OC\Files\Node\File->getContent() at /var/www/html/lib/private/Files/SimpleFS/SimpleFile.php:74
2024-06-29T11:35:11+00:00  OC\Files\SimpleFS\SimpleFile->getContent() at /var/www/html/lib/private/Preview/GeneratorHelper.php:73
2024-06-29T11:35:11+00:00  OC\Preview\GeneratorHelper->getImage() at /var/www/html/lib/private/Preview/Generator.php:190
2024-06-29T11:35:11+00:00  OC\Preview\Generator->generatePreviews() at /var/www/html/lib/private/PreviewManager.php:207
2024-06-29T11:35:11+00:00  OC\PreviewManager->generatePreviews() at /var/www/html/apps/previewgenerator/lib/Command/Generate.php:230
2024-06-29T11:35:11+00:00  OCA\PreviewGenerator\Command\Generate->parseFile() at /var/www/html/apps/previewgenerator/lib/Command/Generate.php:212
2024-06-29T11:35:11+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/apps/previewgenerator/lib/Command/Generate.php:210
2024-06-29T11:35:11+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/apps/previewgenerator/lib/Command/Generate.php:210
2024-06-29T11:35:11+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/apps/previewgenerator/lib/Command/Generate.php:210
2024-06-29T11:35:11+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/apps/previewgenerator/lib/Command/Generate.php:210
2024-06-29T11:35:11+00:00  OCA\PreviewGenerator\Command\Generate->parseFolder() at /var/www/html/apps/previewgenerator/lib/Command/Generate.php:190
2024-06-29T11:35:11+00:00  OCA\PreviewGenerator\Command\Generate->generateUserPreviews() at /var/www/html/apps/previewgenerator/lib/Command/Generate.php:136
2024-06-29T11:35:11+00:00  OCA\PreviewGenerator\Command\Generate->OCA\PreviewGenerator\Command\{closure}() at /var/www/html/lib/private/User/Manager.php:665
2024-06-29T11:35:11+00:00  OC\User\Manager->callForSeenUsers() at /var/www/html/apps/previewgenerator/lib/Command/Generate.php:135
2024-06-29T11:35:11+00:00  OCA\PreviewGenerator\Command\Generate->execute() at /var/www/html/3rdparty/symfony/console/Command/Command.php:298
2024-06-29T11:35:11+00:00  Symfony\Component\Console\Command\Command->run() at /var/www/html/3rdparty/symfony/console/Application.php:1040
2024-06-29T11:35:11+00:00  Symfony\Component\Console\Application->doRunCommand() at /var/www/html/3rdparty/symfony/console/Application.php:301
2024-06-29T11:35:11+00:00  Symfony\Component\Console\Application->doRun() at /var/www/html/3rdparty/symfony/console/Application.php:171
2024-06-29T11:35:11+00:00  Symfony\Component\Console\Application->run() at /var/www/html/lib/private/Console/Application.php:213
2024-06-29T11:35:11+00:00  OC\Console\Application->run() at /var/www/html/console.php:100
2024-06-29T11:35:11+00:00  require_once() at /var/www/html/occ:11
2024-06-29T11:35:11+00:00 
2024-06-29T11:35:11+00:00 preview:generate-all [-p|--path [PATH]] [--] [<user_id>...]
2024-06-29T11:35:11+00:00 
```

Config

```
$ sudo -u www-data php /var/www/html/occ config:list
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.7.4",
        "overwrite.cli.url": ***,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "preview_max_x": 960,
        "preview_max_y": 540,
        "preview_max_filesize_image": 10,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\SVG"
        ],
        "preview_libreoffice_path": "\/snap\/bin\/libreoffice"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.20.0",
            "types": "filesystem"
        },
        "audioplayer": {
            "enabled": "no",
            "installed_version": "3.4.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "2"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "4.7.8",
            "types": ""
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "28.0.0",
            "loopback_tmp_path": "\/",
            "loopback_tmp_scheme": "https",
            "maintenance_run": "0",
            "maintenance_update": "{\"3\":1719660302,\"2\":1719660902,\"1\":1719661202}",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "5.5.3",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "files_metadata": "{\"photos-original_date_time\":{\"value\":null,\"type\":\"int\",\"indexed\":true,\"editPermission\":0},\"photos-size\":{\"value\":null,\"type\":\"array\",\"indexed\":false,\"editPermission\":0},\"photos-exif\":{\"value\":null,\"type\":\"array\",\"indexed\":false,\"editPermission\":0},\"photos-ifd0\":{\"value\":null,\"type\":\"array\",\"indexed\":false,\"editPermission\":0}}",
            "files_metadata_installed": "1",
            "installedat": "1719612653.6727",
            "lastcron": "1719661202",
            "lastupdateResult": "{\"version\":\"29.0.3.4\",\"versionstring\":\"Nextcloud 29.0.3\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-29.0.3.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/29\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=29.0.3\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "lastupdatedat": "1719644351",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "updater.secret.created": "1719643369",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.8.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.29.2",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "duplicatefinder": {
            "enabled": "yes",
            "installed_version": "1.1.10",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "authentication"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "mimetype_version": "28.0.5.1",
            "types": "filesystem"
        },
        "files_archive": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": "filesystem,dav"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.20.0",
            "types": "filesystem",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,swift,\\OC\\Files\\Storage\\SFTP_Key"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.9.0",
            "types": ""
        },
        "files_reminders": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "dav"
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.20.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.21.0",
            "types": "filesystem,dav"
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.17.0",
            "types": "logging"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.13.0",
            "types": "logging"
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.16.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.17.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.16.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.16.3",
            "types": "authentication"
        },
        "onlyoffice": {
            "enabled": "no",
            "installed_version": "9.2.2",
            "types": "prevent_group_restriction"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "lastPlaceMappedUser": "niels",
            "lastPlaceMappingDone": "true",
            "types": "dav,authentication"
        },
        "previewgenerator": {
            "enabled": "yes",
            "installed_version": "5.5.0",
            "types": "filesystem"
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "prevent_group_restriction"
        },
        "recognize": {
            "clusterFaces.lastRun": "1719659809",
            "clusterFaces.status": "true",
            "concurrency.enabled": "false",
            "enabled": "yes",
            "faces.batchSize": "500",
            "faces.enabled": "true",
            "faces.lastFile": "1719660152",
            "faces.status": "true",
            "imagenet.batchSize": "100",
            "imagenet.enabled": "true",
            "imagenet.lastFile": "1719660591",
            "imagenet.status": "true",
            "installed_version": "6.1.1",
            "landmarks.batchSize": "100",
            "landmarks.enabled": "true",
            "landmarks.lastFile": "1719651356",
            "landmarks.status": "true",
            "movinet.batchSize": "20",
            "movinet.enabled": "false",
            "musicnn.batchSize": "100",
            "musicnn.enabled": "false",
            "nice_binary": "\/usr\/bin\/nice",
            "nice_value": "0",
            "node_binary": "\/var\/www\/html\/apps\/recognize\/bin\/node",
            "tensorflow.cores": "0",
            "tensorflow.gpu": "false",
            "tensorflow.purejs": "false",
            "types": "filesystem,dav"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": ""
        },
        "related_resources": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "richdocuments": {
            "enabled": "yes",
            "installed_version": "8.3.8",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "cached_count_filecache": "225430",
            "cached_count_storages": "3",
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.11.1",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.16.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.16.0",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.9.2",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.17.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": ""
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.8.1",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.10.0",
            "types": "filesystem"
        }
    }
}
```

### PR DESCRIPTION
**Pull request by nielstron**
This fixes #487

### CODE REVIEW

File: lib/Command/Generate.php [hunk 1]
```diff
@@ -234,6 +235,8 @@ private function parseFile(File $file): void {
 			} catch (\InvalidArgumentException $e) {
 				$error = $e->getMessage();
 				$this->output->writeln("<error>{$error}</error>");
+			} catch (GenericFileException $e) {
+				$this->output->writeln("<error>GenericFileException</error>");
```
Comment (st3iny) [inline lib/Command/Generate.php]:
```suggestion
			} catch (\InvalidArgumentException | GenericFileException $e) {
				$class = $e::class;
				$error = $e->getMessage();
				$this->output->writeln("<error>{$class}: {$error}</error>");
```

**Review by st3iny — APPROVED** [review]
Looks good to me. I cleaned up the code a bit and added the same logic to the `pre-generate` command.
